
export const LOAD_LEFT_MENUS = "LOAD_LEFT_MENUS";
export const SAVE_LEFT_MENUS = "SAVE_LEFT_MENUS";
export const LEFT_MENU_CLICKED = "LEFT_MENU_CLICKED";
export const OPEN_CLOSE_LEFT_MENU = "OPEN_CLOSE_LEFT_MENU";